version: '3'
services:
  server:
    build: .
    ports:
      - 3000:3000
    container_name: jr-cms-13_server
    depends_on:
      - mongo
    tty: true
    env_file: .env

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    container_name: jr-cms-13_mongo
